version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git
    requires: # buildが成功したら実行する
      - build-test
  build-test:
    docker: # circleci上でのdockerによる実行環境の指定
      - image: cimg/python:3.10.2 # 自分の実行環境に合わせる cimgのpythonであればpipenvがインストール済み
    steps:
      - checkout
      - run: python --version
      - run:
          name: install
          command: pipenv install # Pipfileを用いてインストールする
      - run:
          name: run test
          command: pipenv run pytest --junitxml=test-reports/junit.xml
      - store_test_results: # テスト結果をCircleCIにアップロード
          path: test-reports
workflows:
  version: 2.1
  test_and_deploy: # workflow名
    jobs:
      - build-test
      - deploy:
          requires: # buildが成功したら実行する
            - build-test